### ISSUE TITLE
Update mink-selenium2-driver

### ISSUE THREAD

**Issue by msnassar** [openeuropa/drupal-core-require-dev#85]

**Comment by voidtek** [comment]
We should follow the decision of drupal/core.
https://packagist.org/packages/drupal/core

**Comment by msnassar** [comment]
The branch alias have been changed a hour ago
https://github.com/minkphp/MinkSelenium2Driver/commit/3ab9f315e9ad63cc518ccc72910754fedd6de015


                                                                                                                                                                                                                                                            
  Problem 1                                                                                                                                                                                                                                                    
    - openeuropa/drupal-core-require-dev 8.7.x-dev requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.

**Comment by voidtek** [comment]
Resolved by https://github.com/minkphp/MinkSelenium2Driver/issues/313
